# Generated by Django 5.0.2 on 2024-02-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='upload',
        ),
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.FileField(default='default.png', upload_to='media/'),
        ),
    ]
