# Generated by Django 5.0.2 on 2024-02-10 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_app.article'),
        ),
    ]
