# Generated by Django 5.0.2 on 2024-02-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
