# Generated by Django 5.0.2 on 2024-04-16 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_alter_comment_options_remove_comment_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentArticle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.article', verbose_name='комментарий к статье :'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор комментария'),
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
